apiVersion: 1

datasources:
  - name: Alertmanager
    type: alertmanager
    url: http://localhost:9093
    access: proxy
    # optionally
    basicAuth: false
    # basicAuthUser: my_user
    # basicAuthPassword: test_password