
version: '3.3'

networks:
  coffee_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.100.18.0/24

services:
  sqlimage:
    image: stifstof/coffeesql:latest
    container_name: coffee_sqlcontainer
    restart: unless-stopped
    networks:
      coffee_net:
        ipv4_address: 172.100.18.3
    ports:
      - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - TZ=Europe/Copenhagen
    volumes:
      - coffee-sqldatavolume:/var/lib/mysql

  mqttimage:
    depends_on:
      - sqlimage
    image: stifstof/coffeemqttserver:latest
    container_name: coffee_mqttcontainer
    restart: unless-stopped
    networks:
      coffee_net:
        ipv4_address: 172.100.18.2
    ports:
        - 1883:1883 #mqtt
        - 5000:5000 #flask
    volumes:
      - ./logs:/var/log

  botimage:
    depends_on:
      - mqttimage
    image: stifstof/coffeebot:latest
    container_name: coffee_botcontainer
    volumes:
      - ./logs:/var/log
    restart: unless-stopped
    networks: 
      coffee_net: 
        ipv4_address: 172.100.18.6

  alertmanager:
    image: prom/alertmanager
    container_name: coffee_alertmanager
    volumes:
      - ./alertmanager.yml:/prometheus/alertmanager.yml
      - ./data/alertmanager:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    networks:
      coffee_net:
        ipv4_address: 172.100.18.9

  prometheus:
    depends_on: 
      - loki
    image: prom/prometheus
    container_name: coffee_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      coffee_net:
        ipv4_address: 172.100.18.4
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  promtail:
    image: grafana/promtail:2.3.0
    container_name: coffee_promtail
    volumes:
      - ./logs:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
        coffee_net:
          ipv4_address: 172.100.18.8
    ports:
      - 9080:9080
      - 3500:3500
      - 3600:3600

  loki:
    image: grafana/loki:2.3.0
    container_name: coffee_loki
    restart: unless-stopped
    volumes:
      - ./loki.yml:/etc/loki/local-config.yml
    ports:
      - 3100:3100
      # - 9095:9095
    command: -config.file=/etc/loki/local-config.yml
    networks:
      coffee_net:
        ipv4_address: 172.100.18.7

  loki-canary:
    depends_on: 
      - loki
    image: grafana/loki-canary:2.3.0
    container_name: coffee_loki_canary
    command: [
      "-addr", "172.100.18.7:3100",
      "-size", "1024",
      "-wait", "3m",
      "-interval", "10s",
      "-streamname", "stream", # source for docker driver
      "-streamvalue", "stdout",
      "-labelname", "container_name",
      "-labelvalue", "coffee_loki_canary"
    ]
    networks:
      coffee_net:
        ipv4_address: 172.100.18.10
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  grafana:
    depends_on: 
      - loki-canary
    image: stifstof/iotgrafana:latest
    container_name: coffee_grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      coffee_net:
        ipv4_address: 172.100.18.5
    # volumes:
    #   - ./logs/grafana.log:/var/log/grafana/grafana.log
    # Disabled for sharing with team members due to permission issues with log file locally (sudo chown 472:$USER .logs/grafana.log to fix)


volumes:
  coffee-sqldatavolume:
  prometheus-data: