
version: '3.3'

networks:
  coffee_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.100.18.0/24
        
services:

  botimage:
    image: stifstof/coffeebot:latest
    container_name: coffee_botcontainer
    restart: always
    networks: 
      coffee_net: 
        ipv4_address: 172.100.18.6
    depends_on:
      - mqttimage
    ports:
      - '1884:1883' # mqtt
  
  mqttimage:
    image: stifstof/coffeemqttserver:latest
    container_name: coffee_mqttcontainer
    restart: always
    networks:
      coffee_net:
        ipv4_address: 172.100.18.2
    depends_on:
      - sqlimage
    ports:
        - '1883:1883' #mqtt
        - '5000:5000'

  sqlimage:
    image: stifstof/coffeesql:latest
    container_name: coffee_sqlcontainer
    restart: always
    networks:
      coffee_net:
        ipv4_address: 172.100.18.3
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root
    volumes:
      - coffee-datavolume:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: coffee_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      coffee_net:
        ipv4_address: 172.100.18.4

  grafana:
    image: stifstof/iotgrafana:latest
    container_name: coffee_grafana
    restart: always
    ports:
      - "3000:3000"  
    networks:
      coffee_net:
        ipv4_address: 172.100.18.5
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  coffee-datavolume:
  grafana-storage:
