
version: '3.3'

networks:
  main:

services:

  mqttimage:
    image: stifstof/coffeemqttserver:latest
    container_name: mqttcontainer
    networks:
      - main
    depends_on:
      - sqlimage
    ports:
        - '5001:5001'

  sqlimage:
    image: stifstof/coffeesql:latest
    container_name: coffeesqlcontainer
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root
