
version: '3.3'

networks:
  main:

services:
  
  mqttimage:
    image: stifstof/coffeemqttserver:latest
    container_name: mqttcontainer
    restart: always
    networks:
      - main
    depends_on:
      - sqlimage
    ports:
        - '1883:1883' #mqtt
        - '80:80' #http, maybe needed for a quick visualization option

  sqlimage:
    image: stifstof/coffeesql:latest
    container_name: coffeesqlcontainer
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root
