{
 "title": "CoffeeDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Welcome to our IOT Coffee Grinder Dashboard! \n\nHere you should be able to find relevant data for the daily operations of the device\n\n\n"
  },
  {
   "title": "Todays Grinds",
   "type": "graph",
   "description": "Pull data from MySQL",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT  NOW() AS \"time\", g.GrindName AS metric, r.Count AS value\nFROM Records r, Grinds g\nWHERE g.Id = r.Grind AND r.Date = CURDATE() \nORDER BY g.Id"
    }
   ]
  },
  {
   "title": "CPU Load on server",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "targets": [
    { "expr": "coffeeserver_cpu_load_percent" }
   ]
  },
  {
   "title": "Messages Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coffeeserver_request_duration_milliseconds_count"
    }
   ]
  },
  {
   "title": "Last message recieved on",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 22 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "coffeeserver_last_communication*1000"
    }
   ]
  },
  {
   "title": "Last message recieved on",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 22 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "expr": "coffeeserver_last_communication"
    }
   ]
  }
 ]
}