{
 "title": "CoffeeDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server Hardware Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load on server",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
     "targets": [
      { "expr": "coffeeserver_cpu_load_percent" }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "content": "\n# Welcome to our IOT Coffee Grinder Dashboard! \n\n\nHere you should be able to find relevant data for the daily operations of the device\n\n\n"
  },
  {
   "title": "Todays Grinds",
   "type": "graph",
   "description": "Pull data from MySQL",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT  NOW() AS \"time\", g.GrindName AS metric, r.Count AS value\nFROM Records r, Grinds g\nWHERE g.Id = r.Id AND r.Date = CURDATE()\nORDER BY r.Id ASC\n"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Messages Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coffeeserver_request_duration_milliseconds_count"
    }
   ]
  },
  {
   "title": "Last message recieved on",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "coffeeserver_last_communication*1000"
    }
   ]
  },
  {
   "title": "Last message recieved on",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "coffeeserver_last_communication*1000"
    }
   ]
  },
  { "title": "MySQL Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Grinds Table (Today)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT g.GrindName AS GrindName, r.Count AS Number\nFROM Records r, Grinds g\nWHERE g.Id = r.Id AND r.Date = CURDATE()\nORDER BY r.Id ASC\n"
    }
   ]
  },
  {
   "title": "Grinds Table",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 6, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT g.Id as Id, g.GrindName AS GrindName, g.Duration AS Duration\nFROM Grinds g\nORDER BY g.Id ASC\n"
    }
   ]
  },
  {
   "title": "Records Table",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT r.Date as Date, g.GrindName AS GrindName, r.Count AS Number\nFROM Records r, Grinds g\nWHERE g.Id = r.Id AND r.Date = CURDATE()\nORDER BY r.Id ASC\n"
    }
   ]
  }
 ]
}