{
 "title": "CoffeeDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "content": "\n# Welcome to out Coffee Grinder Dashboard!\n\nHere you should be able to find relevant data for the daily operations of the device\n\n\n"
  },
  {
   "title": "Todays Grinds",
   "type": "graph",
   "description": "Pull data from MySQL",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT  NOW() AS \"time\", g.GrindName AS metric, r.Count AS value\nFROM Records r, Grinds g\nWHERE g.ID = r.ID\nORDER BY r.ID\n"
    }
   ]
  },
  {
   "title": "CPU Load on server",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 16 },
   "targets": [
    { "expr": "coffeeserver_cpu_load_percent" }
   ]
  },
  {
   "title": "Messages Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coffeeserver_request_duration_milliseconds_count"
    }
   ]
  },
  {
   "title": "Last message recieved on",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "coffeeserver_last_communication*1000"
    }
   ]
  },
  {
   "title": "Last message recieved on",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "coffeeserver_last_communication*1000"
    }
   ]
  }
 ]
}