{
 "title": "CoffeeDashboard",
 "time": { "from": "2020-03-10T19:40:00.000Z", "to": "2020-03-18T19:40:00.000Z" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "content": "\n# Welcome to our IoT Coffee Grinder Dashboard! \n\n\nHere you should be able to find relevant data for the daily operations of the embedded device.\n\n\n"
  },
  { "title": "Daily", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Todays Grinds",
   "type": "graph",
   "description": "Pull data from MySQL",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT now() as \"time\", g.GrindName AS metric, r.Count AS value\nFROM Records r, Grinds g\nWHERE g.Id = r.Grind AND r.Date = CURDATE()\nORDER BY r.Id ASC\n"
    }
   ]
  },
  {
   "title": "Weekly",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Week Grinds",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT  NOW() AS \"time\", g.GrindName AS metric, r.Count AS value\nFROM Records r, Grinds g\nWHERE g.Id = r.Grind AND yearweek(DATE(r.Date), 1) = yearweek(curdate(), 1)\nORDER BY g.Id\n"
      }
     ]
    },
    {
     "title": "Grind Trend",
     "type": "graph",
     "description": "Pull data from MySQL",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT UNIX_TIMESTAMP(r.Date) as \"time\", g.GrindName AS metric, r.Count AS value\nFROM Records r, Grinds g\nWHERE g.Id = r.Grind"
      }
     ]
    },
    {
     "title": "Lat weeks grinds",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT  NOW() - 60*60*24 AS \"time\", g.GrindName AS metric, r.Count AS value\nFROM Records r, Grinds g\nWHERE g.Id = r.Grind AND yearweek(DATE(NOW()), 1) = yearweek(curdate(), 1)\nORDER BY g.Id\n\n"
      }
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Messages Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(coffeeserver_request_duration_milliseconds_count)"
    }
   ]
  },
  {
   "title": "Last message recieved on",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 17 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "coffeeserver_last_communication*1000"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 20 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "coffeeserver_last_communication*1000"
    }
   ]
  },
  {
   "title": "Response times MQTT Interceptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": " rate(coffeeserver_request_duration_milliseconds_sum[5m])"
    }
   ]
  },
  {
   "title": "Histogram 80% procentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(coffeeserver_request_duration_milliseconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Server Hardware Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load on server",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
     "targets": [
      { "expr": "coffeeserver_cpu_load_percent" }
     ]
    },
    {
     "title": "Prometheus Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "process_virtual_memory_bytes" }
     ]
    },
    {
     "title": "Prometheus Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[5m])"
      }
     ]
    }
   ]
  },
  { "title": "MySQL Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Grinds Table (Today)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT g.GrindName AS GrindName, r.Count AS Number\nFROM Records r, Grinds g\nWHERE g.Id = r.Grind AND r.Date = CURDATE()\nORDER BY r.Id ASC\n"
    }
   ]
  },
  {
   "title": "Grinds Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT g.Id as Id, g.GrindName AS GrindName, g.Duration AS Duration\nFROM Grinds g\nORDER BY g.Id ASC\n"
    }
   ]
  },
  {
   "title": "Records Table",
   "type": "table",
   "gridPos": { "h": 25, "w": 8, "x": 15, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT r.Id as Id, r.Date as Date, g.GrindName AS GrindName, r.Count AS Number\nFROM Records r, Grinds g\nWHERE g.Id = r.Grind\nORDER BY r.Date DESC, g.Id ASC\n"
    }
   ]
  }
 ]
}