{
 "title": "Loki Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Coffee instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bot Container Log File",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"bot\"}"
    }
   ]
  },
  {
   "title": "Bot Container Log File",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"mqtt\"}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Promtail Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container_name=\"coffee_promtail\"}"
    }
   ]
  },
  {
   "title": "Loki Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{container_name=\"coffee_loki\"}"
    }
   ]
  },
  {
   "title": "Loki Canary Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"coffee_loki_canary\"}"
    }
   ]
  },
  {
   "title": "Grafana Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"coffee_grafana\"}"
    }
   ]
  },
  {
   "title": "Alertmanager Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{container_name=\"coffee_alertmanager\"}"
    }
   ]
  },
  {
   "title": "Prometheus Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "{container_name=\"coffee_prometheus\"}"
    }
   ]
  },
  {
   "title": "MySQL Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{container_name=\"coffee_sqlcontainer\"}"
    }
   ]
  }
 ]
}